# make file to help back things up using bc-chunk-backup.pl

# TODO: consider eliminating some of the intermediate files I use
# below; however, they might actually be useful

# only because these are the last targets (so everything else gets made too)
all: statlist.txt

# exclusions2.txt is a commented/prettified version of the exclusions
# file; this converts it to a usable format
exclusions.txt: exclusions2.txt
	egrep -v '^#|^ *$$' exclusions2.txt > exclusions.txt

# from the full file list, extract fields I want (except extdrive ignored)
bcunix-converted.txt: /bcunix-files.txt
	bc-format2altformat.pl /bcunix-files.txt > bcunix-converted.txt

# TODO: this is ugly, should really loop through drives instead of listing
# them one at a time
extdrive-converted.txt: /mnt/extdrive/extdrive-files.txt
	bc-format2altformat.pl /mnt/extdrive/extdrive-files.txt > extdrive-converted.txt
extdrive2-converted.txt: /mnt/extdrive2/extdrive2-files.txt
	bc-format2altformat.pl /mnt/extdrive2/extdrive2-files.txt > extdrive2-converted.txt
extdrive3-converted.txt: /mnt/extdrive3/extdrive3-files.txt
	bc-format2altformat.pl /mnt/extdrive3/extdrive3-files.txt > extdrive3-converted.txt
extdrive4-converted.txt: /mnt/extdrive4/extdrive4-files.txt
	bc-format2altformat.pl /mnt/extdrive4/extdrive4-files.txt > extdrive4-converted.txt
extdrive5-converted.txt: /mnt/extdrive5/extdrive5-files.txt
	bc-format2altformat.pl /mnt/extdrive5/extdrive5-files.txt > extdrive5-converted.txt

# TODO: this sorting is to join vs old backups, NOT numerical sorting (sigh)
afad.txt: bcunix-converted.txt extdrive-converted.txt extdrive2-converted.txt extdrive3-converted.txt extdrive4-converted.txt extdrive5-converted.txt
	sort *-converted.txt > afad.txt

# The user is expected to provide "previouslydone.txt.srt", by running
# bc-zpaq2exclude.pl on previous zpaq lists (not doing that here,
# because there may be more efficient ways of doing it outside the
# makefile)

# 2147483647 is the largest possible value below, at least on my
# system; this will break if I have over 2 billion+ files (but I'm not
# too worried)

filelist.txt statlist.txt big-by-dir.txt big-by-file.txt: exclusions.txt afad.txt previouslydone.txt.srt
	join --check-order -a 1 -t '\0' afad.txt previouslydone.txt.srt | bc-files-to-backup.pl | egrep -vf exclusions.txt | bc-chunk-backup.pl --debug

# while testing exclusions.txt, it's important to know what big files and
# big directories I'm backing up (so I can potentially exclude them)
# big-by-dir.txt: statlist.txt
# 	bc-total-bytes.pl statlist.txt | sort -nr > big-by-dir.txt
# big-by-file.txt: statlist.txt
# 	sort -k1nr statlist.txt > big-by-file.txt

# it's sometimes useful to see what effect changing exclusions.txt
# will have without redoing the entire chunk backup; "make quick"
# allows for that

# the rm below is because I always end up looking at the wrong file,
# so removing the one I shouldn't look at (since it won't be updated
# until the next true make anyway)
quick: big-by-dir-quick.txt big-by-file-quick.txt statlist-quick.txt
	rm big-by-file.txt big-by-dir.txt
big-by-dir-quick.txt: statlist-quick.txt
	bc-total-bytes.pl statlist-quick.txt | sort -nr > big-by-dir-quick.txt
big-by-file-quick.txt: statlist-quick.txt
	sort -k1nr statlist-quick.txt > big-by-file-quick.txt

# statlist.txt is NOT a dependency since we don't want to rebuild it
statlist-quick.txt: exclusions.txt
	egrep -vf exclusions.txt statlist.txt > statlist-quick.txt
