echo efibootmgr START; dnf provides '*/efibootmgr'; echo efibootmgr END
echo wget START; dnf provides '*/wget'; echo wget END
echo expect START; dnf provides '*/expect'; echo expect END
echo ncftp START; dnf provides '*/ncftp'; echo ncftp END
echo parallel START; dnf provides '*/parallel'; echo parallel END
echo rdate START; dnf provides '*/rdate'; echo rdate END
echo xdotool START; dnf provides '*/xdotool'; echo xdotool END
echo xinetd START; dnf provides '*/xinetd'; echo xinetd END
echo ntpdate START; dnf provides '*/ntpdate'; echo ntpdate END
echo p7zip START; dnf provides '*/p7zip'; echo p7zip END
echo nmap START; dnf provides '*/nmap'; echo nmap END
echo tmpwatch START; dnf provides '*/tmpwatch'; echo tmpwatch END
echo rsyslog START; dnf provides '*/rsyslog'; echo rsyslog END
echo screen START; dnf provides '*/screen'; echo screen END
echo html2ps START; dnf provides '*/html2ps'; echo html2ps END
echo R START; dnf provides '*/R'; echo R END
echo perl-CPAN START; dnf provides '*/perl-CPAN'; echo perl-CPAN END
echo tk START; dnf provides '*/tk'; echo tk END
echo java START; dnf provides '*/java'; echo java END
echo tcsh START; dnf provides '*/tcsh'; echo tcsh END
echo tigervnc START; dnf provides '*/tigervnc'; echo tigervnc END
echo rdesktop START; dnf provides '*/rdesktop'; echo rdesktop END
echo recoll START; dnf provides '*/recoll'; echo recoll END
echo lucene START; dnf provides '*/lucene'; echo lucene END
echo tor START; dnf provides '*/tor'; echo tor END
echo onionshare START; dnf provides '*/onionshare'; echo onionshare END
echo privoxy START; dnf provides '*/privoxy'; echo privoxy END
echo xcalc START; dnf provides '*/xcalc'; echo xcalc END
echo rxvt START; dnf provides '*/rxvt'; echo rxvt END
echo xterm START; dnf provides '*/xterm'; echo xterm END
echo mrtg START; dnf provides '*/mrtg'; echo mrtg END
echo nagios START; dnf provides '*/nagios'; echo nagios END
echo nagios-plugins START; dnf provides '*/nagios-plugins'; echo nagios-plugins END
echo fuse-encfs START; dnf provides '*/fuse-encfs'; echo fuse-encfs END
echo fuse-sshfs START; dnf provides '*/fuse-sshfs'; echo fuse-sshfs END
echo fuse-zip START; dnf provides '*/fuse-zip'; echo fuse-zip END
echo gitfs START; dnf provides '*/gitfs'; echo gitfs END
echo curlftpfs START; dnf provides '*/curlftpfs'; echo curlftpfs END
echo bindfs START; dnf provides '*/bindfs'; echo bindfs END
echo fvwm START; dnf provides '*/fvwm'; echo fvwm END
echo aspell START; dnf provides '*/aspell'; echo aspell END
echo audacity START; dnf provides '*/audacity'; echo audacity END
echo ImageMagick START; dnf provides '*/ImageMagick'; echo ImageMagick END
echo feh START; dnf provides '*/feh'; echo feh END
echo xv START; dnf provides '*/xv'; echo xv END
echo xpdf START; dnf provides '*/xpdf'; echo xpdf END
echo xsane START; dnf provides '*/xsane'; echo xsane END
echo gimp START; dnf provides '*/gimp'; echo gimp END
echo ffmpeg START; dnf provides '*/ffmpeg'; echo ffmpeg END
echo mencoder START; dnf provides '*/mencoder'; echo mencoder END
echo mplayer START; dnf provides '*/mplayer'; echo mplayer END
echo vlc START; dnf provides '*/vlc'; echo vlc END
echo recordmydesktop START; dnf provides '*/recordmydesktop'; echo recordmydesktop END
echo alpine START; dnf provides '*/alpine'; echo alpine END
echo getmail START; dnf provides '*/getmail'; echo getmail END
echo sendmail START; dnf provides '*/sendmail'; echo sendmail END
echo firefox START; dnf provides '*/firefox'; echo firefox END
echo elinks START; dnf provides '*/elinks'; echo elinks END
echo lynx START; dnf provides '*/lynx'; echo lynx END
echo pidgin START; dnf provides '*/pidgin'; echo pidgin END
echo skype START; dnf provides '*/skype'; echo skype END
echo qgis START; dnf provides '*/qgis'; echo qgis END
echo qhull START; dnf provides '*/qhull'; echo qhull END
echo sagemath START; dnf provides '*/sagemath'; echo sagemath END
echo pyephem START; dnf provides '*/pyephem'; echo pyephem END
echo stellarium START; dnf provides '*/stellarium'; echo stellarium END
echo samba START; dnf provides '*/samba'; echo samba END
echo PySolFC START; dnf provides '*/PySolFC'; echo PySolFC END
echo xteddy START; dnf provides '*/xteddy'; echo xteddy END
echo steam START; dnf provides '*/steam'; echo steam END
echo mysql-client START; dnf provides '*/mysql-client'; echo mysql-client END
echo mysql-server START; dnf provides '*/mysql-server'; echo mysql-server END
echo postgresql START; dnf provides '*/postgresql'; echo postgresql END
echo postgresql-server START; dnf provides '*/postgresql-server'; echo postgresql-server END
echo dosbox START; dnf provides '*/dosbox'; echo dosbox END
echo dosemu START; dnf provides '*/dosemu'; echo dosemu END
echo vice START; dnf provides '*/vice'; echo vice END
echo stella START; dnf provides '*/stella'; echo stella END
echo wine START; dnf provides '*/wine'; echo wine END
echo virtualbox START; dnf provides '*/virtualbox'; echo virtualbox END
echo emacs START; dnf provides '*/emacs'; echo emacs END
echo enscript START; dnf provides '*/enscript'; echo enscript END
echo xemacs START; dnf provides '*/xemacs'; echo xemacs END
echo pico START; dnf provides '*/pico'; echo pico END
echo nano START; dnf provides '*/nano'; echo nano END
echo gnumeric START; dnf provides '*/gnumeric'; echo gnumeric END
echo gnuplot START; dnf provides '*/gnuplot'; echo gnuplot END
echo graphviz START; dnf provides '*/graphviz'; echo graphviz END
echo dia START; dnf provides '*/dia'; echo dia END
echo xfig START; dnf provides '*/xfig'; echo xfig END
echo libreoffice START; dnf provides '*/libreoffice'; echo libreoffice END
echo esniper START; dnf provides '*/esniper'; echo esniper END
