echo efibootmgr START; yum provides '*/efibootmgr'; echo efibootmgr END
echo wget START; yum provides '*/wget'; echo wget END
echo expect START; yum provides '*/expect'; echo expect END
echo ncftp START; yum provides '*/ncftp'; echo ncftp END
echo parallel START; yum provides '*/parallel'; echo parallel END
echo rdate START; yum provides '*/rdate'; echo rdate END
echo xdotool START; yum provides '*/xdotool'; echo xdotool END
echo xinetd START; yum provides '*/xinetd'; echo xinetd END
echo ntpdate START; yum provides '*/ntpdate'; echo ntpdate END
echo p7zip START; yum provides '*/p7zip'; echo p7zip END
echo nmap START; yum provides '*/nmap'; echo nmap END
echo tmpwatch START; yum provides '*/tmpwatch'; echo tmpwatch END
echo rsyslog START; yum provides '*/rsyslog'; echo rsyslog END
echo screen START; yum provides '*/screen'; echo screen END
echo html2ps START; yum provides '*/html2ps'; echo html2ps END
echo R START; yum provides '*/R'; echo R END
echo perl-CPAN START; yum provides '*/perl-CPAN'; echo perl-CPAN END
echo tk START; yum provides '*/tk'; echo tk END
echo java START; yum provides '*/java'; echo java END
echo tcsh START; yum provides '*/tcsh'; echo tcsh END
echo tigervnc START; yum provides '*/tigervnc'; echo tigervnc END
echo rdesktop START; yum provides '*/rdesktop'; echo rdesktop END
echo recoll START; yum provides '*/recoll'; echo recoll END
echo lucene START; yum provides '*/lucene'; echo lucene END
echo tor START; yum provides '*/tor'; echo tor END
echo onionshare START; yum provides '*/onionshare'; echo onionshare END
echo privoxy START; yum provides '*/privoxy'; echo privoxy END
echo xcalc START; yum provides '*/xcalc'; echo xcalc END
echo rxvt START; yum provides '*/rxvt'; echo rxvt END
echo xterm START; yum provides '*/xterm'; echo xterm END
echo mrtg START; yum provides '*/mrtg'; echo mrtg END
echo nagios START; yum provides '*/nagios'; echo nagios END
echo nagios-plugins START; yum provides '*/nagios-plugins'; echo nagios-plugins END
echo fuse-encfs START; yum provides '*/fuse-encfs'; echo fuse-encfs END
echo fuse-sshfs START; yum provides '*/fuse-sshfs'; echo fuse-sshfs END
echo fuse-zip START; yum provides '*/fuse-zip'; echo fuse-zip END
echo gitfs START; yum provides '*/gitfs'; echo gitfs END
echo curlftpfs START; yum provides '*/curlftpfs'; echo curlftpfs END
echo bindfs START; yum provides '*/bindfs'; echo bindfs END
echo fvwm START; yum provides '*/fvwm'; echo fvwm END
echo aspell START; yum provides '*/aspell'; echo aspell END
echo audacity START; yum provides '*/audacity'; echo audacity END
echo ImageMagick START; yum provides '*/ImageMagick'; echo ImageMagick END
echo feh START; yum provides '*/feh'; echo feh END
echo xv START; yum provides '*/xv'; echo xv END
echo xpdf START; yum provides '*/xpdf'; echo xpdf END
echo xsane START; yum provides '*/xsane'; echo xsane END
echo gimp START; yum provides '*/gimp'; echo gimp END
echo ffmpeg START; yum provides '*/ffmpeg'; echo ffmpeg END
echo mencoder START; yum provides '*/mencoder'; echo mencoder END
echo mplayer START; yum provides '*/mplayer'; echo mplayer END
echo vlc START; yum provides '*/vlc'; echo vlc END
echo recordmydesktop START; yum provides '*/recordmydesktop'; echo recordmydesktop END
echo alpine START; yum provides '*/alpine'; echo alpine END
echo getmail START; yum provides '*/getmail'; echo getmail END
echo sendmail START; yum provides '*/sendmail'; echo sendmail END
echo firefox START; yum provides '*/firefox'; echo firefox END
echo elinks START; yum provides '*/elinks'; echo elinks END
echo lynx START; yum provides '*/lynx'; echo lynx END
echo pidgin START; yum provides '*/pidgin'; echo pidgin END
echo skype START; yum provides '*/skype'; echo skype END
echo qgis START; yum provides '*/qgis'; echo qgis END
echo qhull START; yum provides '*/qhull'; echo qhull END
echo sagemath START; yum provides '*/sagemath'; echo sagemath END
echo pyephem START; yum provides '*/pyephem'; echo pyephem END
echo stellarium START; yum provides '*/stellarium'; echo stellarium END
echo samba START; yum provides '*/samba'; echo samba END
echo PySolFC START; yum provides '*/PySolFC'; echo PySolFC END
echo xteddy START; yum provides '*/xteddy'; echo xteddy END
echo steam START; yum provides '*/steam'; echo steam END
echo mysql-client START; yum provides '*/mysql-client'; echo mysql-client END
echo mysql-server START; yum provides '*/mysql-server'; echo mysql-server END
echo postgresql START; yum provides '*/postgresql'; echo postgresql END
echo postgresql-server START; yum provides '*/postgresql-server'; echo postgresql-server END
echo dosbox START; yum provides '*/dosbox'; echo dosbox END
echo dosemu START; yum provides '*/dosemu'; echo dosemu END
echo vice START; yum provides '*/vice'; echo vice END
echo stella START; yum provides '*/stella'; echo stella END
echo wine START; yum provides '*/wine'; echo wine END
echo virtualbox START; yum provides '*/virtualbox'; echo virtualbox END
echo emacs START; yum provides '*/emacs'; echo emacs END
echo enscript START; yum provides '*/enscript'; echo enscript END
echo xemacs START; yum provides '*/xemacs'; echo xemacs END
echo pico START; yum provides '*/pico'; echo pico END
echo nano START; yum provides '*/nano'; echo nano END
echo gnumeric START; yum provides '*/gnumeric'; echo gnumeric END
echo gnuplot START; yum provides '*/gnuplot'; echo gnuplot END
echo graphviz START; yum provides '*/graphviz'; echo graphviz END
echo dia START; yum provides '*/dia'; echo dia END
echo xfig START; yum provides '*/xfig'; echo xfig END
echo libreoffice START; yum provides '*/libreoffice'; echo libreoffice END
echo esniper START; yum provides '*/esniper'; echo esniper END
