<?php
	$SPAMTRAP_SEP = array( ".", ".", "-", "_", "_", "", "" );
	$SPAMTRAP_FNAMES = array(
		  "ludivina", "aleida", "lily", "siobhan", "elsa", "ismael"
		, "mona", "dawna", "dong", "dulcie", "vertie", "ashlee"
		, "giuseppina", "augustina", "lourie", "kristle", "jene", "tempie"
		, "roselia", "mohammad", "maire", "pearlie", "erma", "nelly"
		, "rafael", "carlton", "cleopatra", "carmelo", "krysta", "darleen"
		, "magdalen", "rodger", "phylicia", "zulema", "colby", "darius"
		, "mandy", "shameka", "joe", "tammara", "moon", "randal"
		, "saundra", "melissia", "charlette", "zella", "rosy", "cammy"
		, "bettyann", "susanne", "alida", "bridget", "malika", "ileana"
		, "camille", "kittie", "lessie", "rebecka", "miranda", "tasha"
		, "berneice", "cedric", "kortney", "janet", "lorette", "jean"
		, "nicol", "ronna", "margarete", "dot", "ron", "rolf"
		, "janelle", "agnes", "daniell", "boyd", "kent", "cher"
		, "velma", "francesco", "tenesha", "britt", "tressie", "mariano"
		, "georgeanna", "kara", "oretha", "tinisha", "mellissa", "bethany"
		, "tai", "alona", "dena", "autumn", "joana", "daisy"
		, "erick", "shawanda", "pamala", "willis", "dewitt", "meg"
		, "antonina", "erminia", "lee", "mabel", "demarcus", "nelle"
		, "mitch", "loyce", "jonnie", "onie", "fredericka", "florence"
		, "bob", "jeri", "zola", "aide", "kathi", "takako"
		, "nilsa", "lena", "agatha", "kermit", "tammy", "jenelle"
		, "genia", "gabriella", "clare", "ken", "elida", "josette"
		, "nakesha", "henry", "kraig", "rory", "judson", "mary"
		, "lieselotte", "neil", "michal", "eufemia", "jenifer", "gertrud"
		, "earle", "tatum", "rhea", "max", "marcelo", "evelia"
		
	);
	$SPAMTRAP_LNAMES = array(
		  "motola", "stevenson", "jennie", "mccullon", "aylor", "pan"
		, "seniff", "ramire", "harlowe", "leubner", "polson", "deerman"
		, "brandes", "lemasters", "phare", "iacono", "skalka", "bukovac"
		, "ockey", "menzer", "mackenthun", "rosazza", "vizcarrondo", "trouser"
		, "droz", "janower", "woodman", "cabanes", "mcquage", "cabrena"
		, "schlessman", "hengen", "borriello", "formanek", "galeas", "settlemyre"
		, "kausch", "sackett", "kitner", "villecus", "sau", "verbridge"
		, "bullman", "monka", "viniard", "lopes", "molton", "duplessy"
		, "cinnamond", "hager", "falgoust", "katzaman", "rysavy", "macmillen"
		, "chiverton", "len", "fulp", "wrigley", "devitt", "gazzara"
		, "odgen", "gabert", "mccargo", "camey", "uelmen", "haneke"
		, "arevalos", "holland", "scharp", "ramone", "reudink", "bartrum"
		, "ricks", "delamar", "zanetti", "mani", "purple", "kellstrom"
		, "mozee", "piller", "calixte", "hissam", "claybrooks", "albergotti"
		, "roethler", "gilhooly", "slowe", "luckow", "hamelton", "tarman"
		, "kernodle", "willars", "eaddy", "tinnell", "ruwet", "neish"
		, "schellin", "cabaniss", "lineman", "jasmer", "schlup", "geidl"
		, "abood", "friederich", "presta", "fleischner", "bosell", "alzugaray"
		, "kneifel", "mangham", "lorence", "portsche", "giacone", "lowdermilk"
		, "wissink", "deflorio", "dammeyer", "ramones", "chia", "derastel"
		, "napierala", "osterhout", "young", "heavner", "musi", "kindig"
		, "kirberger", "monachino", "rindfleisch", "casiano", "pezzuti", "stamas"
		, "godina", "zipperer", "ung", "abdullai", "frend", "malcom"
		, "voltz", "woodfolk", "morss", "hjermstad", "sanzone", "mosburg"
		, "skimehorn", "karl", "tourtellotte", "angiolelli", "spruit", "easom"
		
	);
?>