/*

COVID-19 virus? nah!

r0 = average number of people a given person can expose to virus per diem

s = susceptibility (chance someone will get virus if exposed)

d = death rate (chance someone will die after getting virus)

p0 = initial population

pop[i] = total population on day i (TODO: ignore deaths and births?)

dead[i] = total number of people who have died from virus (we have in real life)

sick[i] = total number of people who are infected with virus

recov[i] = total number of people who have recovered from virus

*/

<formulas>

r0: 2;
s: 1;
d: 0.04;
p0: 10000;

sick[0] : 1;
pop[0]: p0;
recov[0] : 0;
dead[0] : 0;

sick[i] := float(sick[i-1]*r0*s*(1-recov[i-1]/pop[i-1]));
    
dead[i] := float(dead[i-1] + sick[i-1]*d);

recov[i] := float(recov[i-1] + sick[i-1]*(1-d));

pop[i] := float(pop[i-1] - dead[i-1]);

</formulas>

/*

day 0: 1 sick person

day 1: 1 + 2 = 3 sick people, 0.04 dead, 0.96 recovered, p0 - 0.04

day 2: 