float num = 1.; // particles generated per time interval
float life = 2000.; // life of each particle, in time units
float size_start = 0.01; // starting size of each particle
float size_end = 0.02; // ending size of each particle
VECTOR color_start = {1.,1.,0}; // starting color of each particle
VECTOR color_end = {1.,0.,0}; // ending color of each particle
VECTOR dir = {0,0.002,0}; // direction in which particles are emitted
VECTOR turb_dir = {0.002,0.002,0.01}; // randomness of direction
VECTOR emitter = {0,0,0}; // location of particle emitter
VECTOR gravity = {0,0,0}; // the force of gravity
