# creates executables from C code
/home/barrycarter/bin/seps: bc-find-under6.c
	gcc -I /home/barrycarter/SPICE/cspice/include bc-find-under6.c -o /home/barrycarter/bin/seps /home/barrycarter/SPICE/cspice/lib/cspice.a -lm
